
import type { LucideIcon } from "lucide-react";
import {
  Globe,
  PlayCircle,
  Mail,
  Github,
  HelpCircle,
  Linkedin,
  MessageCircle,
  Slack,
  FileText,
  Code,
  StickyNote,
  PenTool,
  Image,
  Film,
  ShoppingCart,
  ShoppingBag,
  Music,
  MessageSquare,
  HardDrive,
  FileText as DocsIcon,
  Table,
  Calendar,
  Code2,
  Award,
  Braces
} from "lucide-react";

export const defaultApps = [
  { name: "Google", url: "https://google.com", icon: "Globe" },
  { name: "YouTube", url: "https://youtube.com", icon: "PlayCircle" },
  { name: "Gmail", url: "https://mail.google.com", icon: "Mail" },
  { name: "GitHub", url: "https://github.com", icon: "Github" },
  { name: "Stack Overflow", url: "https://stackoverflow.com", icon: "HelpCircle" },
  { name: "LinkedIn", url: "https://linkedin.com", icon: "Linkedin" },
  { name: "Twitter (X)", url: "https://x.com", icon: "MessageCircle" },
  { name: "Slack", url: "https://slack.com", icon: "Slack" },
  { name: "Medium", url: "https://medium.com", icon: "FileText" },
  { name: "Dev.to", url: "https://dev.to", icon: "Code" },
  { name: "Notion", url: "https://notion.so", icon: "StickyNote" },
  { name: "Figma", url: "https://figma.com", icon: "PenTool" },
  { name: "Canva", url: "https://canva.com", icon: "Image" },
  { name: "Netflix", url: "https://netflix.com", icon: "Film" },
  { name: "Amazon", url: "https://amazon.com", icon: "ShoppingCart" },
  { name: "Flipkart", url: "https://flipkart.com", icon: "ShoppingBag" },
  { name: "Spotify", url: "https://spotify.com", icon: "Music" },
  { name: "WhatsApp Web", url: "https://web.whatsapp.com", icon: "MessageSquare" },
  { name: "Google Drive", url: "https://drive.google.com", icon: "HardDrive" },
  { name: "Google Docs", url: "https://docs.google.com", icon: "FileText" },
  { name: "Google Sheets", url: "https://sheets.google.com", icon: "Table" },
  { name: "Google Calendar", url: "https://calendar.google.com", icon: "Calendar" },
  { name: "LeetCode", url: "https://leetcode.com", icon: "Code2" },
  { name: "HackerRank", url: "https://hackerrank.com", icon: "Award" },
  { name: "CodePen", url: "https://codepen.io", icon: "Braces" },
];

